apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-k8s
  template:
    metadata:
      labels:
        app: nginx-k8s
    spec:
      containers:
      - name: nginx
        image: viswa96/kubernetes:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s-service
spec:
  type: NodePort
  selector:
    app: nginx-k8s
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31254
